### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by paulopires16** [walmins/autoswitch-hiveOS#1]
Traceback (most recent call last):
  File "D:\workspace-python\hiveOS\src\eypiay-example.py", line 233, in <module>
    api.run()
  File "D:\workspace-python\hiveOS\src\eypiay-example.py", line 49, in run
    result = m()
  File "D:\workspace-python\hiveOS\src\eypiay-example.py", line 142, in getRigs
    rigs = self.request(params)
  File "D:\workspace-python\hiveOS\src\eypiay-example.py", line 98, in request
    curl.perform()
pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')

**Comment by walmins** [comment]
work fine for me!
are you fixed it?

**Comment by paulopires16** [comment]
Yes walmins, just adding these 2 lines:
	curl.setopt(pycurl.SSL_VERIFYPEER, 0)   
	curl.setopt(pycurl.SSL_VERIFYHOST, 0)

**Comment by walmins** [comment]
ok, thanks
